name: u_nidos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_colorpicker: ^1.0.3
  cloud_firestore: ^4.15.9
  connectivity_plus: ^5.0.2
  intl: ^0.20.2
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/icono.png"